<a href="https://colab.research.google.com/github/rhehgus02/ESAA/blob/main/%ED%9A%8C%EA%B7%801_%EC%97%B0%EC%8A%B5%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. 단순 선형 회귀 분석**
- 전복의 나이를 예측하는 선형회귀모델을 생성하세요.
- 전복의 ‘성별’, ‘키’, ‘지름’, ‘높이’, ‘전체무게’, ‘몸통무게’, ‘내장무게’, ‘껍질무게’를 이용해 ‘껍질의 고리 수’를 예측한 뒤, **예측된 ‘껍질의 고리 수’에 1.5를 더하면 전복의 나이**가 됩니다.

In [1]:
# 기본 모듈 불러오기
import numpy as np
import pandas as pd

**1) 데이터 load 및 변형**

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
# 데이터 로드
data = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/ESAA/data/abalone.csv")
print(data.shape)
data.head()

(4177, 9)

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

In [4]:
# 성별 M은 Male, F는 Female, I는 Infant 이므로 따로 열 만들기
for label in "MFI":
    data[label] = data["Sex"] == label
data.drop('Sex', axis=1, inplace=True)
data.head()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings,M,F,I
0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15,True,False,False
1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7,True,False,False
2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9,False,True,False
3,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10,True,False,False
4,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7,False,False,True

**2) X, y 선택**
: y는 Rings열, X는 Rings열을 제외한 나머지를 선택하되 전부 실수가 되도록 한다.

In [5]:
# X,y 데이터 선택
y = data['Rings']
X = data.drop('Rings', axis=1)
X = X.astype(float)

In [6]:
X.head(3)

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,M,F,I
0,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.15,1.0,0.0,0.0
1,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.07,1.0,0.0,0.0
2,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.21,0.0,1.0,0.0

 **3) train/test set 분리**

In [7]:
# 필요한 모듈 불러오기
from sklearn.model_selection import train_test_split

In [8]:
# train과 test set 분리 (train:test = 7:3 비율로)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

**4) 선형회귀모델 생성, 모델 예측치 구하기**

In [9]:
# 필요한 모듈 불러오기
from sklearn.linear_model import LinearRegression

In [10]:
# 선형회귀모델 생성 및 훈련
mymodel = LinearRegression()
mymodel.fit(X_train, y_train)

LinearRegression()

In [11]:
# 모델 예측치 구하기
y_pred = mymodel.predict(X_test)

# 모델 예측치를 활용해 최종적으로 전복의 나이를 예측
y_pred = y_pred + 1.5

**5) 모델 평가: MSE, RMSE, R2 score, corr 구하기**

In [12]:
# 필요한 모듈 불러오기
from sklearn.metrics import mean_squared_error, r2_score

- MSE, RMSE

In [13]:
# mse, rmse
mse = mean_squared_error(y_test, y_pred)
rmse = np.sqrt(mse)

print(f'MSE: {mse:.4f}, RMSE: {rmse:.4f}')

MSE: 8.0025, RMSE: 2.8289

- R2 score

In [14]:
#R2 score 측정
R2_score = r2_score(y_test, y_pred)
print(f'R2 score: {R2_score:.4f}')

R2 score: 0.2468

- 회귀 절편값

In [15]:
# 회귀 절편 값
np.round(mymodel.intercept_, 2)

19700956701555.0

- 회귀 계수 값

In [16]:
# 회귀 계수 값
np.round(mymodel.coef_, 2)

array([ 4.20000000e-01,  6.94000000e+00,  2.42800000e+01,  8.29000000e+00,
       -1.84800000e+01, -1.07600000e+01,  8.43000000e+00, -1.97009567e+13,
       -1.97009567e+13, -1.97009567e+13])

- 상관계수

Hint: corr 함수 이용.

In [17]:
data.corr()

,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings,M,F,I
Length,1.000000,0.986812,0.827554,0.925261,0.897914,0.903018,0.897706,0.556720,0.236543,0.309666,-0.551465
Diameter,0.986812,1.000000,0.833684,0.925452,0.893162,0.899724,0.905330,0.574660,0.240376,0.318626,-0.564315
Height,0.827554,0.833684,1.000000,0.819221,0.774972,0.798319,0.817338,0.557467,0.215459,0.298421,-0.518552
Whole weight,0.925261,0.925452,0.819221,1.000000,0.969405,0.966375,0.955355,0.540390,0.252038,0.299741,-0.557592
Shucked weight,0.897914,0.893162,0.774972,0.969405,1.000000,0.931961,0.882617,0.420884,0.251793,0.263991,-0.521842
Viscera weight,0.903018,0.899724,0.798319,0.966375,0.931961,1.000000,0.907656,0.503819,0.242194,0.308444,-0.556081
Shell weight,0.897706,0.905330,0.817338,0.955355,0.882617,0.907656,1.000000,0.627574,0.235391,0.306319,-0.546953
Rings,0.556720,0.574660,0.557467,0.540390,0.420884,0.503819,0.627574,1.000000,0.181831,0.250279,-0.436063
M,0.236543,0.240376,0.215459,0.252038,0.251793,0.242194,0.235391,0.181831,1.000000,-0.512528,-0.522541
F,0.309666,0.318626,0.298421,0.299741,0.263991,0.308444,0.306319,0.250279,-0.512528,1.000000,-0.464298
I,-0.551465,-0.564315,-0.518552,-0.557592,-0.521842,-0.556081,-0.546953,-0.436063,-0.522541,-0.464298,1.000000

# **2. Polynomial features**

In [18]:
# PolynomialFeatures 라이브러리 호출
from sklearn.preprocessing import PolynomialFeatures

In [19]:
# 임의 데이터 생성

X = np.arange(6).reshape(3, 2)

df = pd.DataFrame(X)
df.columns = ['x_1','x_2']
df

   x_1  x_2
0    0    1
1    2    3
2    4    5

In [20]:
# 차원은 2로 설정
# fit_transform 메소드를 통해 데이터 변환
# PolynomialFeatures로 변환 된 데이터를 데이터 프레임 형태로 변환

poly = PolynomialFeatures(degree=2)
df2 = poly.fit_transform(df)
df2 = pd.DataFrame(df2) # PolynomialFeatures로 변환 된 데이터를 데이터 프레임 형태로 변환
df2

     0    1    2     3     4     5
0  1.0  0.0  1.0   0.0   0.0   1.0
1  1.0  2.0  3.0   4.0   6.0   9.0
2  1.0  4.0  5.0  16.0  20.0  25.0

In [21]:
# df_poly의 컬럼을 1,x1,x2,x1^2,x1*x2,x2^2 로 변경
column_names = ['1','x1','x2','x1^2','x1*x2','x2^2']
df2.columns = column_names
df2

     1   x1   x2  x1^2  x1*x2  x2^2
0  1.0  0.0  1.0   0.0    0.0   1.0
1  1.0  2.0  3.0   4.0    6.0   9.0
2  1.0  4.0  5.0  16.0   20.0  25.0